In [1]:
import pandas as pd
import numpy as np

In [304]:
df=pd.read_csv('final_dataset.csv')
df.head()

,order_date,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue
0,2022-04-13,Books,128.75,10,4,North America,UPI,3.5,443,115.88,463.52
1,2023-03-12,Fashion,302.60,20,5,Asia,Credit Card,3.7,475,242.08,1210.40
2,2022-09-28,Sports,495.80,20,2,Europe,UPI,4.4,183,396.64,793.28
3,2022-04-17,Books,371.95,15,4,Middle East,UPI,5.0,212,316.16,1264.64
4,2022-03-13,Beauty,201.68,0,4,Middle East,UPI,4.6,308,201.68,806.72

In [305]:
df.describe()

,price,discount_percent,quantity_sold,rating,review_count,discounted_price,total_revenue
count,49714.000000,49714.000000,49714.000000,49714.000000,49714.000000,49714.000000,49714.000000
mean,251.201797,13.404474,2.987891,2.995679,249.280585,217.451105,647.639565
std,142.389680,9.840360,1.411285,1.154140,144.262036,126.259903,511.909676
min,5.010000,0.000000,1.000000,1.000000,0.000000,3.530000,3.840000
25%,127.082500,5.000000,2.000000,2.000000,125.000000,108.982500,239.040000
50%,251.355000,15.000000,3.000000,3.000000,250.000000,214.565000,500.090000
75%,374.320000,20.000000,4.000000,4.000000,374.000000,321.135000,956.700000
max,499.990000,30.000000,5.000000,5.000000,499.000000,499.890000,2235.950000

In [306]:
df['customer_region'].unique()

array(['North America', 'Asia', 'Europe', 'Middle East'], dtype=object)

In [307]:
#Define Target Variable (High Demand)
#Threshold in terms of quantity_sold makes overfitted model with accuracy 1.0...So on checking with all viable columns...

threshold=df['total_revenue'].median()
df['High_Demand']=(df['total_revenue']>threshold)
df['High_Demand'].astype(int)
df.head()

,order_date,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue,High_Demand
0,2022-04-13,Books,128.75,10,4,North America,UPI,3.5,443,115.88,463.52,False
1,2023-03-12,Fashion,302.60,20,5,Asia,Credit Card,3.7,475,242.08,1210.40,True
2,2022-09-28,Sports,495.80,20,2,Europe,UPI,4.4,183,396.64,793.28,True
3,2022-04-17,Books,371.95,15,4,Middle East,UPI,5.0,212,316.16,1264.64,True
4,2022-03-13,Beauty,201.68,0,4,Middle East,UPI,4.6,308,201.68,806.72,True

In [308]:
df=df.drop('order_date',axis=1)

In [310]:
df=df.drop(['payment_method','review_count','rating'],axis=1)

In [311]:
#Encoding Categorical Features...

df = pd.get_dummies(df, drop_first=False)
df.head()

,price,discount_percent,quantity_sold,discounted_price,total_revenue,High_Demand,product_category_Beauty,product_category_Books,product_category_Electronics,product_category_Fashion,product_category_Home & Kitchen,product_category_Sports,customer_region_Asia,customer_region_Europe,customer_region_Middle East,customer_region_North America
0,128.75,10,4,115.88,463.52,False,False,True,False,False,False,False,False,False,False,True
1,302.60,20,5,242.08,1210.40,True,False,False,False,True,False,False,True,False,False,False
2,495.80,20,2,396.64,793.28,True,False,False,False,False,False,True,False,True,False,False
3,371.95,15,4,316.16,1264.64,True,False,True,False,False,False,False,False,False,True,False
4,201.68,0,4,201.68,806.72,True,True,False,False,False,False,False,False,False,True,False

In [312]:
bool_cols = df.select_dtypes(include='bool').columns

df[bool_cols] = df[bool_cols].astype(int)

In [313]:
df.head()

,price,discount_percent,quantity_sold,discounted_price,total_revenue,High_Demand,product_category_Beauty,product_category_Books,product_category_Electronics,product_category_Fashion,product_category_Home & Kitchen,product_category_Sports,customer_region_Asia,customer_region_Europe,customer_region_Middle East,customer_region_North America
0,128.75,10,4,115.88,463.52,0,0,1,0,0,0,0,0,0,0,1
1,302.60,20,5,242.08,1210.40,1,0,0,0,1,0,0,1,0,0,0
2,495.80,20,2,396.64,793.28,1,0,0,0,0,0,1,0,1,0,0
3,371.95,15,4,316.16,1264.64,1,0,1,0,0,0,0,0,0,1,0
4,201.68,0,4,201.68,806.72,1,1,0,0,0,0,0,0,0,1,0

In [348]:
df.columns

Index(['price', 'discount_percent', 'quantity_sold', 'discounted_price',
       'total_revenue', 'High_Demand', 'product_category_Beauty',
       'product_category_Books', 'product_category_Electronics',
       'product_category_Fashion', 'product_category_Home & Kitchen',
       'product_category_Sports', 'customer_region_Asia',
       'customer_region_Europe', 'customer_region_Middle East',
       'customer_region_North America'],
      dtype='object')

In [314]:
#Split Features and Target...

x = df.drop(['High_Demand','total_revenue'],axis=1)
y = df['High_Demand']

In [315]:
x.shape

(49714, 14)

In [316]:
y.shape

(49714,)

In [317]:
#Train-Test Split...

from sklearn.model_selection import train_test_split

In [318]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1000)

In [319]:
print('X_train shape',x_train.shape)
print('X_test shape',x_test.shape)
print('Y_train shape',y_train.shape)
print('Y_test shape',y_test.shape)

X_train shape (39771, 14)
X_test shape (9943, 14)
Y_train shape (39771,)
Y_test shape (9943,)

In [320]:
#Logistic Regression Implementation...

from sklearn.linear_model import LogisticRegression

In [321]:
logr = LogisticRegression()
logr.fit(x_train,y_train)
y_pred=logr.predict(x_test)

C:\Users\moham\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [322]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [323]:
print("Accuracy Score : ",accuracy_score(y_test,y_pred))
print("Precision Score : ",precision_score(y_test,y_pred))
print("Recall Score : ",recall_score(y_test,y_pred))
print("F1 Score : ",f1_score(y_test,y_pred))

Accuracy Score :  0.9055617016996882
Precision Score :  0.9063245823389021
Recall Score :  0.906865671641791
F1 Score :  0.9065950462548493

In [324]:
#Naive Bayes Implementation..

from sklearn.naive_bayes import GaussianNB

In [325]:
model_nb = GaussianNB()
model_nb.fit(x_train, y_train)
y_pred_nb = model_nb.predict(x_test)

In [326]:
print("Accuracy Score : ",accuracy_score(y_test,y_pred_nb))
print("Precision Score : ",precision_score(y_test,y_pred_nb))
print("Recall Score : ",recall_score(y_test,y_pred_nb))
print("F1 Score : ",f1_score(y_test,y_pred_nb))

Accuracy Score :  0.868550739213517
Precision Score :  0.8783068783068783
Recall Score :  0.8589054726368159
F1 Score :  0.8684978368045075

In [327]:
#KNN Implementation..

from sklearn.neighbors import KNeighborsClassifier

In [328]:
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(x_train, y_train)
y_pred_knn = model_knn.predict(x_test)

In [329]:
print("Accuracy Score : ",accuracy_score(y_test,y_pred_knn))
print("Precision Score : ",precision_score(y_test,y_pred_knn))
print("Recall Score : ",recall_score(y_test,y_pred_knn))
print("F1 Score : ",f1_score(y_test,y_pred_knn))

Accuracy Score :  0.9519259780750277
Precision Score :  0.9449990213348992
Recall Score :  0.9607960199004976
F1 Score :  0.9528320505229919

In [330]:
from sklearn.linear_model import LinearRegression

In [331]:
linr=LinearRegression()

In [332]:
x=df.drop(['total_revenue'],axis=1)
y=df['total_revenue']

In [333]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1000)

In [334]:
print('X_train shape',x_train.shape)
print('X_test shape',x_test.shape)
print('Y_train shape',y_train.shape)
print('Y_test shape',y_test.shape)

X_train shape (39771, 15)
X_test shape (9943, 15)
Y_train shape (39771,)
Y_test shape (9943,)

In [335]:
linr.fit(x_train,y_train)

LinearRegression()

In [336]:
linr.score(x_test,y_test)

0.8884181506931093

In [337]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

In [338]:
y_pred=linr.predict(x_test)

In [339]:
print("MSE Value:",mean_squared_error(y_test,y_pred))
print("MAE Value:",mean_absolute_error(y_test,y_pred))
print("RMSE Value:",np.sqrt(mean_squared_error(y_test,y_pred)))
print("R2 Score Value:",r2_score(y_test,y_pred))

MSE Value: 29203.536054657354
MAE Value: 135.96617176730325
RMSE Value: 170.89042119047326
R2 Score Value: 0.8884181506931093

In [340]:
df.head()

,price,discount_percent,quantity_sold,discounted_price,total_revenue,High_Demand,product_category_Beauty,product_category_Books,product_category_Electronics,product_category_Fashion,product_category_Home & Kitchen,product_category_Sports,customer_region_Asia,customer_region_Europe,customer_region_Middle East,customer_region_North America
0,128.75,10,4,115.88,463.52,0,0,1,0,0,0,0,0,0,0,1
1,302.60,20,5,242.08,1210.40,1,0,0,0,1,0,0,1,0,0,0
2,495.80,20,2,396.64,793.28,1,0,0,0,0,0,1,0,1,0,0
3,371.95,15,4,316.16,1264.64,1,0,1,0,0,0,0,0,0,1,0
4,201.68,0,4,201.68,806.72,1,1,0,0,0,0,0,0,0,1,0

In [342]:
linr.predict([[371.95,15,4,316.16,1,0,1,0,0,0,0,0,0,1,0]])

C:\Users\moham\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([1171.79560615])

In [344]:
logr.predict([[128.75,10,4,115.88,0,1,0,0,0,0,0,0,0,1]])

C:\Users\moham\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [345]:
import pickle

# Save Linear Regression
with open("linear_model.pkl", "wb") as f:
    pickle.dump(linr, f)

print("Linear Regression model saved successfully.")

Linear Regression model saved successfully.

In [346]:
# Save Logistic Regression
with open("logistic_model.pkl", "wb") as f:
    pickle.dump(logr, f)

print("Logistic Regression model saved successfully.")

Logistic Regression model saved successfully.